# Generated by Django 5.0.6 on 2024-06-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='status',
            field=models.CharField(default='Pending', max_length=255),
        ),
    ]
